spring:
  application:
    name: recipes

  datasource:
    url: jdbc:postgresql://localhost:5432/recipes
    username: postgres
    password: postgres

  flyway:
    enabled: true
    schemas: public
    baseline-on-migrate: true

management:
  endpoints:
    jmx:
      exposure:
        include: health,info
