create table users
(
    user_id    varchar(100) not null primary key,
    first_name varchar(50),
    last_name  varchar(100)
);
insert into users (user_id, first_name, last_name) values ('mary@gmail.com', 'Mary', 'Tom');
insert into users (user_id, first_name, last_name) values ('abc@gmail.com', 'abc', 'Tom');
insert into users (user_id, first_name, last_name) values ('xyz@gmail.com', 'xyz', 'Tom');

create table recipe
(
    id                  bigint generated by default as identity primary key,
    description         text,
    instruction         text,
    name                varchar(100),
    user_id             varchar(100),
    vegetarian          boolean,
    number_of_servings  integer
);

create table ingredient
(
    id        bigint generated by default as identity primary key,
    name      varchar(255),
    recipe_id bigint constraint fk_rcp_id references recipe
);
